### ISSUE TITLE
Doesn't work on Win 10

### ISSUE THREAD

**Issue by zbigniewcebula** [Arlorean/Voxels#2]
Installation goes without problems... but no thumbnails available.

**Comment by zbigniewcebula** [comment]
Solved with starting _"C:\Program Files (x86)\Voxels\srm.exe"_.

**Comment by Arlorean** [comment]
Glad you got it working. There is a thumbnail cache that Windows Explorer uses that I'm not clearing during the install, so you'll probably find new files show correctly but old ones may not until the cache is cleaned out.

[This article should help you reset the cache](https://www.windowscentral.com/how-reset-thumbnail-cache-windows-10).

Removing the **%LocalAppData%\Microsoft\Windows\Explorer\thumbcache_*.db** files is essentially what it says.

I'll close this issue if that's OK.
