### ISSUE TITLE
Possible to convert entire directory instead of singular VOX?

### ISSUE THREAD

**Issue by lazyRares** [Arlorean/Voxels#3]
Basically, im trying to generate a bunch of VOX Files' PNG's. (Around 2800 Vox Files) But using the current setup Command Line Arguements only supports one file, I tried rewriting it to allow this but i dont know enough about how this works to try that. So im just wondering if im missing something that i can input to allow this... I remember doing it a long time ago but i dont remember how.

**Comment by Arlorean** [comment]
I could modify the code to optionally take a directory or a voxel file. I’m not sure if I’ll get around to it soon though unfortunately. 

Edit: The command line allows multiple files so you could pass “a*.vox”, “b*.vox”, etc. to get around the shell limits on command line length.

**Comment by lazyRares** [comment]
> I could modify the code to optionally take a directory or a voxel file. I’m not sure if I’ll get around to it soon though unfortunately.
> 
> Edit: The command line allows multiple files so you could pass “a*.vox”, “b*.vox”, etc. to get around the shell limits on command line length.

I tried the possible solution but it threw "illegal characters" error, so i might just write a program to output every Vox files name to a file and paste it all in there. Since if you put a vox file seperated by a space it will generate a preview for all of them Ex: evertides_painting_17.vox evertides_chair_red.vox

**Comment by Arlorean** [comment]
You could try this in Powershell. `cd` to the directory you want to get PNG files for and then run this:
`Get-ChildItem -name *.vox | foreach {& 'C:\Program Files (x86)\Voxels\Voxels.CommandLine.exe' $_}`

**Comment by lazyRares** [comment]
I came up with a sort of backwards way to circumvent this, I made a program that outputs all the vox names to a text file, and then. I edited your code so it allows for manual input of where it should output the images, now i can just paste in the block of outputted VOX names and itll go through and generate each image for it and output it to a single folder designated. It's very hacky though as you need to manually input the path.

On that side note, is it okay if we publish a built version of the program primarily made for use for the game "Teardown"? Since we needed this to generate previews of props in the game for a mod. Proper credit will of course be given.

**Comment by Arlorean** [comment]
Glad you got it working in the end. Good luck with you project, I hope this helps.

**Comment by Arlorean** [comment]
Yes, please feel free to publish a built version. You might want to fork this repo on Github to do it, but whatever works for you. Teardown is on my Steam wishlist. I must get around to buying it one day soon, it looks great.

**Comment by Arlorean** [comment]
This is now fixed and will be in the v1.5 release.
